(function(){
	function MNrep(x) {
		var re = x;
		re = re.replace(/WordPress/ig,'WordPress');
		re = re.replace(/Wi-Fi/ig,'Wi-Fi');
		re = re.replace(/WiFi/ig,'Wi-Fi');
		re = re.replace(/WLAN/ig,'WLAN');
		re = re.replace(/Mac Book/ig,'MacBook');
		re = re.replace(/Mac Air/ig,'MacBook Air');
		re = re.replace(/OS X/ig,'OS X');
		re = re.replace(/OSX/ig,'OS X');
		re = re.replace(/国内/ig,'中国');
		re = re.replace(/JavaScript/ig,'JavaScript');
		re = re.replace(/Java/ig,'Java');
		re = re.replace(/AJAX/ig,'AJAX');
		re = re.replace(/jQuery/ig,'jQuery');
		re = re.replace(/Python/ig,'Python');
		re = re.replace(/Ruby/ig,'Ruby');
		re = re.replace(/Perl/ig,'Perl');
		re = re.replace(/GNU/ig,'GNU');
		re = re.replace(/Photoshop/ig,'Photoshop');
		re = re.replace(/Pixelmator/ig,'Pixelmator');
		re = re.replace(/Android/ig,'Android');
		re = re.replace(/Evernote/ig,'Evernote');
		re = re.replace(/Linux/ig,'Linux');
		re = re.replace(/ThinkPad/ig,'ThinkPad');
		re = re.replace(/MacBook Air/ig,'MacBook Air');
		re = re.replace(/MacBookAir/ig,'MacBook Air');
		re = re.replace(/MacBook Pro/ig,'MacBook Pro');
		re = re.replace(/MacBookPro/ig,'MacBook Pro');
		re = re.replace(/MacBook/ig,'MacBook');
		re = re.replace(/Mac Pro/ig,'Mac Pro');
		re = re.replace(/MacPro/ig,'Mac Pro');
		re = re.replace(/Mac mini/ig,'Mac mini');
		re = re.replace(/Macmini/ig,'Mac mini');
		re = re.replace(/iMac/ig,'iMac');
		re = re.replace(/Mac/ig,'Mac');
		re = re.replace(/iTunes Store/ig,'iTunes Store');
		re = re.replace(/iTunes/ig,'iTunes');
		re = re.replace(/iCloud/ig,'iCloud');
		re = re.replace(/App Store/ig,'App Store');
		re = re.replace(/Mac App Store/ig,'Mac App Store');
		re = re.replace(/Retina display/ig,'Retina display');
		re = re.replace(/Safari/ig,'Safari');
		re = re.replace(/Chrome/ig,'Chrome');
		re = re.replace(/Firefox/ig,'Firefox');
		re = re.replace(/Opera/ig,'Opera');
		re = re.replace(/Logic Pro/ig,'Logic Pro');
		re = re.replace(/Logic Pro X/ig,'Logic Pro X');
		re = re.replace(/Aperture/ig,'Aperture');
		re = re.replace(/Final Cut Pro/ig,'Final Cut Pro');
		re = re.replace(/Final Cut/ig,'Final Cut');
		re = re.replace(/iPhoto/ig,'iPhoto');
		re = re.replace(/iMovie/ig,'iMovie');
		re = re.replace(/GarageBand/ig,'GarageBand');
		re = re.replace(/iPad/ig,'iPad');
		re = re.replace(/iPhone/ig,'iPhone');
		re = re.replace(/iPhone4/ig,'iPhone 4');
		re = re.replace(/iPhone 4s/ig,'iPhone 4s');
		re = re.replace(/iPhone4s/ig,'iPhone 4s');
		re = re.replace(/iPhone5/ig,'iPhone 5');
		re = re.replace(/iPhone 5s/ig,'iPhone 5s');
		re = re.replace(/iPhone5s/ig,'iPhone 5s');
		re = re.replace(/iPod/ig,'iPod');
		re = re.replace(/itouch/ig,'iPod touch');
		re = re.replace(/iPod touch/ig,'iPod touch');
		re = re.replace(/iPod nano/ig,'iPod nano');
		re = re.replace(/iPod classic/ig,'iPod classic');
		re = re.replace(/iPod shuffle/ig,'iPod shuffle');
		re = re.replace(/iPod/ig,'iPod');
		re = re.replace(/GitHub/ig,'GitHub');
		re = re.replace(/GoAgentX/ig,'GoAgentX');
		re = re.replace(/GoAgent/ig,'GoAgent');
		re = re.replace(/Quora/ig,'Quora');
		re = re.replace(/Twitter/ig,'Twitter');
		re = re.replace(/Facebook/ig,'Facebook');
		re = re.replace(/Google/ig,'Google');
		re = re.replace(/YouTube/ig,'YouTube');
		re = re.replace(/IFTTT/ig,'IFTTT');
		return re;
	};
	var y = new XMLHttpRequest();
	y.open('GET','http://dync.joyneop.com/zhihu/mn/server_letter_spacing.php',false);
	y.send();
	eval(y.responseText);
	document.getElementsByClassName("zu-edit-button")[1].click();
	// document.getElementsByTagName("select")[0].options[0].value = document.getElementsByTagName("select")[0].options[3].value;
	document.getElementsByTagName("select")[0].options[0].value = "错别字去死 http://zhuanlan.zhihu.com/pointless/19736685";
	var t = document.getElementsByClassName("zm-editable-editor-input")[0].value;
	document.getElementsByClassName("zm-editable-editor-input")[0].value = MNrep(t);
	pangu.page_spacing();
	document.getElementsByClassName("zg-r3px")[1].click();
})();